# Generated by Django 5.2.10 on 2026-01-20 16:20

import autographs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Autograph',
            fields=[
                ('id', models.CharField(default=autographs.models.generate_autograph_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='autographs/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='autographs', to='autographs.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
