# Generated by Django 5.2.10 on 2026-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='autograph',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
