# Generated by Django 5.2.10 on 2026-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0003_autograph_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='autograph',
            name='size',
            field=models.CharField(default='8×10 in (20×25 cm)', max_length=50),
        ),
    ]
