# Generated by Django 5.2.10 on 2026-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0004_autograph_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='autograph',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='autographs/thumbs/'),
        ),
    ]
